# Generated by Django 3.0.4 on 2020-03-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolinks', '0002_uri_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uri',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
