# Generated by Django 3.0.4 on 2020-03-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('ident', models.IntegerField()),
                ('first_name', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_bot', models.BooleanField()),
                ('language_code', models.CharField(blank=True, max_length=255, null=True)),
                ('web_enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
