# Generated by Django 3.0.4 on 2020-03-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='ident',
            field=models.IntegerField(unique=True),
        ),
    ]
