# Generated by Django 3.0.4 on 2020-03-28 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_telegramuser_web_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='web_enabled',
        ),
    ]
