# Generated by Django 3.0.4 on 2020-03-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_remove_telegramuser_web_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='receive_unknown',
            field=models.BooleanField(default=False),
        ),
    ]
