# Generated by Django 3.0.4 on 2020-03-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(help_text='Escribe /start para el mensaje de bienvenida', max_length=255, unique=True)),
                ('text', models.TextField()),
            ],
        ),
    ]
