# Generated by Django 3.0.4 on 2020-03-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_web',
            field=models.BooleanField(default=False, help_text='Si se muestra en portada en la web'),
        ),
    ]
